Test.expect(0-5, -5);
Test.expect(false, !true);
Test.expect(true, !false);
Test.expect(false, !!false);
Test.expect(true, !!!false);
let n = 5;
Test.expect(5, n);
Test.expect(4, --n);
Test.expect(5, ++n);
Test.expect(5, n--);
Test.expect(4, n++);