expect(-1, "hello friends".lastIndexOf());
expect(9, "hello friends".lastIndexOf("e"));
expect(-1, "hello friends".lastIndexOf("e", -7));
expect(9, "hello friends".lastIndexOf("e", 100));
expect(13, "hello friends".lastIndexOf(""));
expect(-1, "hello friends".lastIndexOf("Z"));
expect(-1, "hello friends".lastIndexOf("serenity"));
expect(4, "hello friends".lastIndexOf("", 4));
expect(6, "hello serenity friends".lastIndexOf("serenity"));
expect(23, "hello serenity friends serenity".lastIndexOf("serenity"));
expect(6, "hello serenity friends serenity".lastIndexOf("serenity", 14));
expect(0, "".lastIndexOf(""));
expect(0, "".lastIndexOf("", 1));
expect(0, "".lastIndexOf("", -1));
expect(0, "hello friends serenity".lastIndexOf("h", 10));
expect(3, "hello friends serenity".lastIndexOf("l", 4));
expect(12, "hello friends serenity".lastIndexOf("s", 13));
expect(-1, "hello".lastIndexOf("serenity"));
s = "😀";
expect(0, s.lastIndexOf("😀"));
expect(0, s.lastIndexOf("\ud83d"));
expect(1, s.lastIndexOf("\ude00"));
expect(-1, s.lastIndexOf("a"));