expect("hello friends", "hello friends".slice());
expect("ello friends", "hello friends".slice(1));
expect("hello", "hello friends".slice(0, 5));
expect("", "hello friends".slice(13, 6));
expect("hello", "hello friends".slice("", 5));
expect("", "hello friends".slice(3, 3));
expect("s", "hello friends".slice(-1, 13));
expect("hello friends", "hello friends".slice(0, 50));
expect("hello", "hello friends".slice(0, "5"));
expect("friends", "hello friends".slice("6", "13"));
expect("friends", "hello friends".slice(-7));
expect("", "hello friends".slice(1000));
expect("hello friends", "hello friends".slice(-1000));
expect("😀", "😀".slice());
expect("😀", "😀".slice(0));
expect("\ude00", "😀".slice(1));
expect("\ud83d", "😀".slice(0, 1));
expect("😀", "😀".slice(0, 2));