let value;
value = -0;
Test.expect(1, ++value);
value = -0;
++value;
Test.expect(1, value);
value = "-0";
Test.expect(1, ++value);
value = "-0";
++value;
Test.expect(1, value);
value = 0;
Test.expect(1, ++value);
value = 0;
++value;
Test.expect(1, value);
value = "0";
Test.expect(1, ++value);
value = "0";
++value;
Test.expect(1, value);
value = 41.66;
Test.expect(42.66, ++value);
value = 41.66;
++value;
Test.expect(42.66, value);
value = "41.66";
Test.expect(42.66, ++value);
value = "41.66";
++value;
Test.expect(42.66, value);
value = -54.21;
Test.expect(-53.21, ++value);
value = -54.21;
++value;
Test.expect(-53.21, value);
value = "-54.21";
Test.expect(-53.21, ++value);
value = "-54.21";
++value;
Test.expect(-53.21, value);
value = 7;
Test.expect(8, ++value);
value = 7;
++value;
Test.expect(8, value);
value = "7";
Test.expect(8, ++value);
value = "7";
++value;
Test.expect(8, value);
value = -92;
Test.expect(-91, ++value);
value = -92;
++value;
Test.expect(-91, value);
value = "-92";
Test.expect(-91, ++value);
value = "-92";
++value;
Test.expect(-91, value);
value = 16n;
Test.expect(17n, ++value);
value = 16n;
++value;
Test.expect(17n, value);
value = "16n";
Test.expect(NaN, ++value);
value = "16n";
++value;
Test.expect(NaN, value);
value = -32n;
Test.expect(-31n, ++value);
value = -32n;
++value;
Test.expect(-31n, value);
value = "-32n";
Test.expect(NaN, ++value);
value = "-32n";
++value;
Test.expect(NaN, value);
value = null;
Test.expect(1, ++value);
value = null;
++value;
Test.expect(1, value);
value = "null";
Test.expect(NaN, ++value);
value = "null";
++value;
Test.expect(NaN, value);
value = undefined;
Test.expect(NaN, ++value);
value = undefined;
++value;
Test.expect(NaN, value);
value = "undefined";
Test.expect(NaN, ++value);
value = "undefined";
++value;
Test.expect(NaN, value);
value = NaN;
Test.expect(NaN, ++value);
value = NaN;
++value;
Test.expect(NaN, value);
value = "NaN";
Test.expect(NaN, ++value);
value = "NaN";
++value;
Test.expect(NaN, value);
value = Infinity;
Test.expect(Infinity, ++value);
value = Infinity;
++value;
Test.expect(Infinity, value);
value = "Infinity";
Test.expect(Infinity, ++value);
value = "Infinity";
++value;
Test.expect(Infinity, value);
value = -Infinity;
Test.expect(-Infinity, ++value);
value = -Infinity;
++value;
Test.expect(-Infinity, value);
value = "-Infinity";
Test.expect(-Infinity, ++value);
value = "-Infinity";
++value;
Test.expect(-Infinity, value);
value = true;
Test.expect(2, ++value);
value = true;
++value;
Test.expect(2, value);
value = "true";
Test.expect(NaN, ++value);
value = "true";
++value;
Test.expect(NaN, value);
value = false;
Test.expect(1, ++value);
value = false;
++value;
Test.expect(1, value);
value = "false";
Test.expect(NaN, ++value);
value = "false";
++value;
Test.expect(NaN, value);
value = {};
Test.expect(NaN, ++value);
value = {};
++value;
Test.expect(NaN, value);
value = "{}";
Test.expect(NaN, ++value);
value = "{}";
++value;
Test.expect(NaN, value);
value = [];
Test.expect(1, ++value);
value = [];
++value;
Test.expect(1, value);
value = "[]";
Test.expect(NaN, ++value);
value = "[]";
++value;
Test.expect(NaN, value);
value = "hello";
Test.expect(NaN, ++value);
value = "hello";
++value;
Test.expect(NaN, value);
value = "１２３";
Test.expect(NaN, ++value);
value = "１２３";
++value;
Test.expect(NaN, value);
value = "-１２３";
Test.expect(NaN, ++value);
value = "-１２３";
++value;
Test.expect(NaN, value);
value = 0xB2;
Test.expect(179, ++value);
value = 0xB2;
++value;
Test.expect(179, value);
value = "0xB2";
Test.expect(179, ++value);
value = "0xB2";
++value;
Test.expect(179, value);
value = 0b1101;
Test.expect(14, ++value);
value = 0b1101;
++value;
Test.expect(14, value);
value = "0b1101";
Test.expect(14, ++value);
value = "0b1101";
++value;
Test.expect(14, value);
value = 0o777;
Test.expect(512, ++value);
value = 0o777;
++value;
Test.expect(512, value);
value = "0o777";
Test.expect(512, ++value);
value = "0o777";
++value;
Test.expect(512, value);