Test.expect(true, "hello world".includes("hello"))
Test.expect(false, "hello world".includes("hello", 100))
Test.expect(true, "hello world".includes("hello", -10))
Test.expect(true, "hello world".includes("world", 6))
Test.expect(false, "hello world".includes("hello", 6))
Test.expect(true, "hello world false".includes(false))
Test.expect(true, "hello 10 world".includes(10))
Test.expect(true, "hello world undefined".includes())
Test.expect(true, "😀".includes("😀"))
Test.expect(true, "😀".includes("\ud83d"))
Test.expect(true, "😀".includes("\ude00"))
Test.expect(false, "😀".includes("a"))