expect(true, "hello world".includes("hello"))
expect(false, "hello world".includes("hello", 100))
expect(true, "hello world".includes("hello", -10))
expect(true, "hello world".includes("world", 6))
expect(false, "hello world".includes("hello", 6))
expect(true, "hello world false".includes(false))
expect(true, "hello 10 world".includes(10))
expect(true, "hello world undefined".includes())
expect(true, "😀".includes("😀"))
expect(true, "😀".includes("\ud83d"))
expect(true, "😀".includes("\ude00"))
expect(false, "😀".includes("a"))