Test.expect(-1, "hello friends".lastIndexOf());
Test.expect(9, "hello friends".lastIndexOf("e"));
Test.expect(-1, "hello friends".lastIndexOf("e", -7));
Test.expect(9, "hello friends".lastIndexOf("e", 100));
Test.expect(13, "hello friends".lastIndexOf(""));
Test.expect(-1, "hello friends".lastIndexOf("Z"));
Test.expect(-1, "hello friends".lastIndexOf("serenity"));
Test.expect(4, "hello friends".lastIndexOf("", 4));
Test.expect(6, "hello serenity friends".lastIndexOf("serenity"));
Test.expect(23, "hello serenity friends serenity".lastIndexOf("serenity"));
Test.expect(6, "hello serenity friends serenity".lastIndexOf("serenity", 14));
Test.expect(0, "".lastIndexOf(""));
Test.expect(0, "".lastIndexOf("", 1));
Test.expect(0, "".lastIndexOf("", -1));
Test.expect(0, "hello friends serenity".lastIndexOf("h", 10));
Test.expect(3, "hello friends serenity".lastIndexOf("l", 4));
Test.expect(12, "hello friends serenity".lastIndexOf("s", 13));
Test.expect(-1, "hello".lastIndexOf("serenity"));
const s = "😀";
Test.expect(0, s.lastIndexOf("😀"));
Test.expect(0, s.lastIndexOf("\ud83d"));
Test.expect(1, s.lastIndexOf("\ude00"));
Test.expect(-1, s.lastIndexOf("a"));