let s = "hello friends";
Test.expect(6, s.indexOf("friends"));
Test.expect(-1, s.indexOf("enemies"));
Test.expect(6, s.indexOf("friends", 0));
Test.expect(-1, s.indexOf("enemies", 0));
Test.expect(6, s.indexOf("friends", 4));
Test.expect(6, s.indexOf("friends", 6));
Test.expect(-1, s.indexOf("friends", 7));
Test.expect(-1, s.indexOf("friends", 8));
Test.expect(-1, s.indexOf("enemies", 2));
Test.expect(-1, s.indexOf("enemies", 7));
Test.expect(1, s.indexOf("e"));
Test.expect(1, s.indexOf("e", 0));
Test.expect(9, s.indexOf("e", 2));

s = "😀";
Test.expect(0, s.indexOf("😀"));
Test.expect(0, s.indexOf("\ud83d"));
Test.expect(1, s.indexOf("\ude00"));
Test.expect(-1, s.indexOf("a"));