Test.expect("hello friends", "hello friends".slice());
Test.expect("ello friends", "hello friends".slice(1));
Test.expect("hello", "hello friends".slice(0, 5));
Test.expect("", "hello friends".slice(13, 6));
Test.expect("hello", "hello friends".slice("", 5));
Test.expect("", "hello friends".slice(3, 3));
Test.expect("s", "hello friends".slice(-1, 13));
Test.expect("hello friends", "hello friends".slice(0, 50));
Test.expect("hello", "hello friends".slice(0, "5"));
Test.expect("friends", "hello friends".slice("6", "13"));
Test.expect("friends", "hello friends".slice(-7));
Test.expect("", "hello friends".slice(1000));
Test.expect("hello friends", "hello friends".slice(-1000));
Test.expect("😀", "😀".slice());
Test.expect("😀", "😀".slice(0));
Test.expect("\ude00", "😀".slice(1));
Test.expect("\ud83d", "😀".slice(0, 1));
Test.expect("😀", "😀".slice(0, 2));