expect("hello friends".substring(), "hello friends");
expect("hello friends".substring(1), "ello friends");
expect("hello friends".substring(0, 5), "hello");
expect("hello friends".substring(13, 6), "friends");
expect("hello friends".substring("", 5), "hello");
expect("hello friends".substring(3, 3), "");
expect("hello friends".substring(-1, 13), "hello friends");
expect("hello friends".substring(0, 50), "hello friends");
expect("hello friends".substring(0, "5"), "hello");
expect("hello friends".substring("6", "13"), "friends");
expect("😀".substring(), "😀");
expect("😀".substring(0), "😀");
expect("😀".substring(0, 2), "😀");
expect("😀".substring(0, 1), "\ud83d");
expect("😀".substring(1, 2), "\ude00");
expect("😀".substring(2, 2), "");