Test.expect("hello friends".substring(), "hello friends");
Test.expect("hello friends".substring(1), "ello friends");
Test.expect("hello friends".substring(0, 5), "hello");
Test.expect("hello friends".substring(13, 6), "friends");
Test.expect("hello friends".substring("", 5), "hello");
Test.expect("hello friends".substring(3, 3), "");
Test.expect("hello friends".substring(-1, 13), "hello friends");
Test.expect("hello friends".substring(0, 50), "hello friends");
Test.expect("hello friends".substring(0, "5"), "hello");
Test.expect("hello friends".substring("6", "13"), "friends");
Test.expect("😀".substring(), "😀");
Test.expect("😀".substring(0), "😀");
Test.expect("😀".substring(0, 2), "😀");
Test.expect("😀".substring(0, 1), "\ud83d");
Test.expect("😀".substring(1, 2), "\ude00");
Test.expect("😀".substring(2, 2), "");