expect("hello world", "   hello world  ".trim());
expect("hello world", "hello world   ".trim());
expect("hello world", "   hello world".trim());
expect("hello world", "\thello world\t".trim());
expect("hello world", "\thello world".trim());
expect("hello world", "hello world\t".trim());
expect("hello world", "\rhello world\r".trim());
expect("hello world", "\rhello world".trim());
expect("hello world", "hello world\r".trim());
expect("hello world", "\rhello world\n".trim());
expect("hello world", "\r\thello world".trim());
expect("hello world", "hello world\r\n".trim());
expect("hello world", "  \thello world\r\n".trim());
expect("hello world", "\n\t\thello world\r\n".trim());
expect("hello world", "\n\t\thello world\t\t".trim());
expect("hello world", "   hello world".trimStart());
expect("hello world   ", "hello world   ".trimStart());
expect("hello world   ", "    hello world   ".trimStart());
expect("hello world", "\thello world".trimStart());
expect("hello world\t", "hello world\t".trimStart());
expect("hello world\t", "\thello world\t".trimStart());
expect("hello world", "\rhello world".trimStart());
expect("hello world\r", "hello world\r".trimStart());
expect("hello world\r", "\rhello world\r".trimStart());
expect("hello world", "hello world   ".trimEnd());
expect("   hello world", "   hello world".trimEnd());
expect("   hello world", "   hello world   ".trimEnd());
expect("hello world", "hello world\t".trimEnd());
expect("\thello world", "\thello world".trimEnd());
expect("\thello world", "\thello world\t".trimEnd());
expect("hello world", "hello world\r".trimEnd());
expect("\rhello world", "\rhello world".trimEnd());
expect("\rhello world", "\rhello world\r".trimEnd());
expect("hello world", "hello world\n".trimEnd());
expect("\r\nhello world", "\r\nhello world".trimEnd());
expect("\rhello world", "\rhello world\r\n".trimEnd());
expect("_\u180E", "_\u180E".trim());
expect("\u180E", "\u180E".trim());
expect("\u180E_", "\u180E_".trim());
expect("_😀", "_😀".trim());
expect("😀", "😀".trim());
expect("😀_", "😀_".trim());