Test.equals(-0.1, JSON.parse("-0.1"));
Test.equals(" ", JSON.parse("\" \""));
Test.equals("", JSON.parse("\"\""));
Test.equals("asd", JSON.parse("\"asd\""));
Test.equals([-0], JSON.parse("[-0]"));
Test.equals([-1], JSON.parse("[-1]"));
Test.equals([-123], JSON.parse("[-123]"));
Test.equals([-1e-78], JSON.parse("[-0.000000000000000000000000000000000000000000000000000000000000000000000000000001]\r\n"));
Test.equals(["￾"], JSON.parse("[\"\\uFFFE\"]"));
Test.equals([" "], JSON.parse("[\" \"]"));
Test.equals([" "], JSON.parse("[\" \"]"));
Test.equals([","], JSON.parse("[\"\\u002c\"]"));
Test.equals([""], JSON.parse("[\"\"]"));
Test.equals([""], JSON.parse("[\"\"]"));
Test.equals(["ࠡ"], JSON.parse("[\"\\u0821\"]"));
Test.equals(["​"], JSON.parse("[\"\\u200B\"]"));
Test.equals(["⁤"], JSON.parse("[\"\\u2064\"]"));
Test.equals(["\""], JSON.parse("[\"\\\"\"]"));
Test.equals(["\""], JSON.parse("[\"\\u0022\"]"));
Test.equals(["\"\\/\b\f\n\r\t"], JSON.parse("[\"\\\"\\\\\\/\\b\\f\\n\\r\\t\"]"));
Test.equals(["\\"], JSON.parse("[\"\\u005C\"]"));
Test.equals(["\\a"], JSON.parse("[\"\\\\a\"]"));
Test.equals(["\\n"], JSON.parse("[\"\\\\n\"]"));
Test.equals(["\\u0000"], JSON.parse("[\"\\\\u0000\"]"));
Test.equals(["\u0000"], JSON.parse("[\"\\u0000\"]"));
Test.equals(["\u0012"], JSON.parse("[\"\\u0012\"]"));
Test.equals(["`Īካ"], JSON.parse("[\"\\u0060\\u012a\\u12AB\"]"));
Test.equals(["⍂㈴⍂"], JSON.parse("[\"⍂㈴⍂\"]"));
Test.equals(["𝄞"], JSON.parse("[\"\\uD834\\uDd1e\"]"));
Test.equals(["😹💍"], JSON.parse("[\"\\ud83d\\ude39\\ud83d\\udc8d\"]"));
Test.equals(["€𝄞"], JSON.parse("[\"€𝄞\"]"));
Test.equals(["a"], JSON.parse("[\"a\"]"));
Test.equals(["a"], JSON.parse("[\"a\"]\r\n"));
Test.equals(["a/*b*/c/*d//e"], JSON.parse("[\"a/*b*/c/*d//e\"]"));
Test.equals(["aa"], JSON.parse("[\"aa\"]"));
Test.equals(["asd "], JSON.parse("[\"asd \"]"));
Test.equals(["asd"], JSON.parse("[ \"asd\"]"));
Test.equals(["asd"], JSON.parse("[\"asd\"]"));
Test.equals(["aクリス"], JSON.parse("[\"\\u0061\\u30af\\u30EA\\u30b9\"]"));
Test.equals(["ģ"], JSON.parse("[\"\\u0123\"]"));
Test.equals(["new line"], JSON.parse("[\"new\\u00A0line\"]"));
Test.equals(["new\nline"], JSON.parse("[\"new\\u000Aline\"]"));
Test.equals(["π"], JSON.parse("[\"π\"]"));
Test.equals(["ꙭ"], JSON.parse("[\"\\uA66D\"]"));
Test.equals(["𐐷"], JSON.parse("[\"\\uD801\\udc37\"]"));
Test.equals(["﷐"], JSON.parse("[\"\\uFDD0\"]"));
Test.equals(["𛿿"], JSON.parse("[\"𛿿\"]"));
Test.equals(["🿾"], JSON.parse("[\"\\uD83F\\uDFFE\"]"));
Test.equals(["􏿾"], JSON.parse("[\"\\uDBFF\\uDFFE\"]"));
Test.equals(["􏿿"], JSON.parse("[\"\\uDBFF\\uDFFF\"]"));
Test.equals(["􏿿"], JSON.parse("[\"􏿿\"]"));
Test.equals(["￿"], JSON.parse("[\"\\uFFFF\"]"));
Test.equals(["￿"], JSON.parse("[\"￿\"]"));
Test.equals([[]], JSON.parse("[[]   ]"));
Test.equals([], JSON.parse(" [] "));
Test.equals([], JSON.parse("[]"));
Test.equals([0.01], JSON.parse("[1E-2]"));
Test.equals([0.01], JSON.parse("[1e-2]"));
Test.equals([0], JSON.parse("[0e+1]"));
Test.equals([0], JSON.parse("[0e1]"));
Test.equals([1,null,null,null,2], JSON.parse("[1,null,null,null,2]"));
Test.equals([1.23456e+80], JSON.parse("[123.456e78]"));
Test.equals([1.23e+47], JSON.parse("[123e45]"));
Test.equals([1.23e+67], JSON.parse("[123e65]"));
Test.equals([1], JSON.parse(" [1]"));
Test.equals([1], JSON.parse("[1\r\n]"));
Test.equals([100], JSON.parse("[1E+2]"));
Test.equals([100], JSON.parse("[1e+2]"));
Test.equals([123.456789], JSON.parse("[123.456789]"));
Test.equals([123], JSON.parse("[123]"));
Test.equals([1e+22], JSON.parse("[1E22]"));
Test.equals([2], JSON.parse("[2] "));
Test.equals([200], JSON.parse("[20e1]"));
Test.equals([4], JSON.parse("[ 4]"));
Test.equals([false], JSON.parse("[false]"));
Test.equals([null,1,"1",{}], JSON.parse("[null, 1, \"1\", {}]"));
Test.equals([null], JSON.parse("[null]"));
Test.equals([true], JSON.parse("[true]"));
Test.equals({"":0}, JSON.parse("{\"\":0}"));
Test.equals({"a":"b"}, JSON.parse("{\"a\":\"b\",\"a\":\"b\"}"));
Test.equals({"a":"b"}, JSON.parse("{\r\n\"a\": \"b\"\r\n}"));
Test.equals({"a":"c"}, JSON.parse("{\"a\":\"b\",\"a\":\"c\"}"));
Test.equals({"a":[]}, JSON.parse("{\"a\":[]}"));
Test.equals({"asd":"sdf","dfg":"fgh"}, JSON.parse("{\"asd\":\"sdf\", \"dfg\":\"fgh\"}"));
Test.equals({"asd":"sdf"}, JSON.parse("{\"asd\":\"sdf\"}"));
Test.equals({"foo\u0000bar":42}, JSON.parse("{\"foo\\u0000bar\": 42}"));
Test.equals({"min":-1e+28,"max":1e+28}, JSON.parse("{ \"min\": -1.0e+28, \"max\": 1.0e+28 }"));
Test.equals({"title":"Полтора Землекопа"}, JSON.parse("{\"title\":\"\\u041f\\u043e\\u043b\\u0442\\u043e\\u0440\\u0430 \\u0417\\u0435\\u043c\\u043b\\u0435\\u043a\\u043e\\u043f\\u0430\" }"));
Test.equals({"x":[{"id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}],"id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}, JSON.parse("{\"x\":[{\"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}], \"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}"));
Test.equals({}, JSON.parse("{}"));
Test.equals(42, JSON.parse("42"));
Test.equals(false, JSON.parse("false"));
Test.equals(null, JSON.parse("null"));
Test.equals(true, JSON.parse("true"));
Test.expectError("SyntaxError", "Bad control character '\\r' in string literal in JSON", () => JSON.parse("[\"new\r\nline\"]"));
Test.expectError("SyntaxError", "Bad control character '\\t' in string literal in JSON", () => JSON.parse("[\"\t\"]"));
Test.expectError("SyntaxError", "Bad control character '\\v' in string literal in JSON", () => JSON.parse("[\"\u000ba\"\\f]"));
Test.expectError("SyntaxError", "Bad control character '\\x00' in string literal in JSON", () => JSON.parse("[\"a\u0000a\"]"));

Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\{[\"\\{[\"\\{[\"\\{"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\\t\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\\u0000\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\🌀\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\a\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\uD800\\uD800\\x\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\x00\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("[\"\\�\"]"));
Test.expectError("SyntaxError", "Bad escaped character in JSON", () => JSON.parse("\"\\UA66D\""));

Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\u00A\"]"));
Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\uD800\\u\"]"));
Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\uD800\\u1\"]"));
Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\uD800\\u1x\"]"));
Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\uD834\\uDd\"]"));
Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\uqqqq\"]"));
Test.expectError("SyntaxError", "Bad Unicode escape in JSON", () => JSON.parse("[\"\\u�\"]"));

Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0.3e]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0.3e+]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0E]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0e]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0e+-1]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0E+]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[0e+]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[1.0e-]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[1.0e]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[1.0e+]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[1ea]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[1eE2]"));
Test.expectError("SyntaxError", "Exponent part is missing a number in JSON", () => JSON.parse("[1e�]"));

Test.expectError("SyntaxError", "No number after minus sign in JSON", () => JSON.parse("[- 1]"));
Test.expectError("SyntaxError", "No number after minus sign in JSON", () => JSON.parse("[-.123]"));
Test.expectError("SyntaxError", "No number after minus sign in JSON", () => JSON.parse("[-]"));
Test.expectError("SyntaxError", "No number after minus sign in JSON", () => JSON.parse("[-foo]"));
Test.expectError("SyntaxError", "No number after minus sign in JSON", () => JSON.parse("[-Infinity]"));
Test.expectError("SyntaxError", "No number after minus sign in JSON", () => JSON.parse("[-NaN]"));

Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[-2.]"));
Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[0.e1]"));
Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[1.]"));
Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[2.e-3]"));
Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[2.e+3]"));
Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[2.e3]"));
Test.expectError("SyntaxError", "Unterminated fractional number in JSON", () => JSON.parse("[9.e+]"));

Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("[\"\\\"]"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("[\"\\\\\\\"]"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("[\"\\uD800\\\"]"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("[\"a"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("[\"asd]"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("{\"a"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("{\"a\":\"a"));
Test.expectError("SyntaxError", "Unterminated string in JSON", () => JSON.parse("\""));

Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse(" "));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse(""));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[ false, nul"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[ false, tru"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[ true, fals"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("["));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[{"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[{}"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[\"\""));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[\"\\"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[\"a\",\r\n4\r\n,1,"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[\"a\""));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[\"x\""));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[1,"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[1,\r\n1\r\n,1"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("[1"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("{"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("{\"\":"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("{\"a\":"));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("{\"a\""));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("{\"asd\":\"asd\""));
Test.expectError("SyntaxError", "Unexpected end of JSON input", () => JSON.parse("{\"x\": true,"));

Test.expectError("SyntaxError", "Unexpected non-whitespace character ',' after JSON", () => JSON.parse("[\"\"],"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '[' after JSON", () => JSON.parse("[][]"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character ']' after JSON", () => JSON.parse("[\"x\"]]"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character ']' after JSON", () => JSON.parse("[1]]"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character ']' after JSON", () => JSON.parse("1]"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '}' after JSON", () => JSON.parse("{}}"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '@' after JSON", () => JSON.parse("2@"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '/' after JSON", () => JSON.parse("{\"a\":\"b\"}/"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '/' after JSON", () => JSON.parse("{\"a\":\"b\"}/**/"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '/' after JSON", () => JSON.parse("{\"a\":\"b\"}/**//"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '/' after JSON", () => JSON.parse("{\"a\":\"b\"}//"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '\\x00' after JSON", () => JSON.parse("123\u0000"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '#' after JSON", () => JSON.parse("{\"a\":\"b\"}#"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character '#' after JSON", () => JSON.parse("{\"a\":\"b\"}#{}"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character 'x' after JSON", () => JSON.parse("[1]x"));
Test.expectError("SyntaxError", "Unexpected non-whitespace character 'x' after JSON", () => JSON.parse("\"\"x"));
Test.expectError("SyntaxError", `Unexpected non-whitespace character '"' after JSON`, () => JSON.parse("{\"a\": true} \"x\""));

Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("[   , \"\"]"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("[,]"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("[,1]"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("[\"x\",,]"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("[1,,]"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("[1,,2]"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("{,"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("{\"a\":\"b\",,\"c\":\"d\"}"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("{\"id\":0,,,,,}"));
Test.expectError("SyntaxError", "Unexpected token ',' in JSON", () => JSON.parse("{\"x\", null}"));
Test.expectError("SyntaxError", "Unexpected token ','", () => JSON.parse("[,"));
Test.expectError("SyntaxError", "Unexpected token ':' in JSON", () => JSON.parse("[\"\": 1]"));
Test.expectError("SyntaxError", "Unexpected token ':' in JSON", () => JSON.parse("[1:2]"));
Test.expectError("SyntaxError", "Unexpected token ':' in JSON", () => JSON.parse("{:\"b\"}"));
Test.expectError("SyntaxError", "Unexpected token ':'", () => JSON.parse("{\"x\"::\"b\"}"));
Test.expectError("SyntaxError", "Unexpected token '.' in JSON", () => JSON.parse("[-1.0.]"));
Test.expectError("SyntaxError", "Unexpected token '.' in JSON", () => JSON.parse("[.-1]"));
Test.expectError("SyntaxError", "Unexpected token '.' in JSON", () => JSON.parse("[.2e-3]"));
Test.expectError("SyntaxError", "Unexpected token '.' in JSON", () => JSON.parse("[0.1.2]"));
Test.expectError("SyntaxError", "Unexpected token '.'", () => JSON.parse("[.123]"));
Test.expectError("SyntaxError", "Unexpected token '[' in JSON", () => JSON.parse("[3[4]]"));
Test.expectError("SyntaxError", "Unexpected token '[' in JSON", () => JSON.parse("{[: \"x\"}\r\n"));
Test.expectError("SyntaxError", "Unexpected token '[' in JSON", () => JSON.parse("{["));
Test.expectError("SyntaxError", "Unexpected token ']' in JSON", () => JSON.parse("[\"\",]"));
Test.expectError("SyntaxError", "Unexpected token ']' in JSON", () => JSON.parse("[1,]"));
Test.expectError("SyntaxError", "Unexpected token ']' in JSON", () => JSON.parse("[fals]"));
Test.expectError("SyntaxError", "Unexpected token ']' in JSON", () => JSON.parse("[nul]"));
Test.expectError("SyntaxError", "Unexpected token ']' in JSON", () => JSON.parse("[tru]"));
Test.expectError("SyntaxError", "Unexpected token ']' in JSON", () => JSON.parse("{]"));
Test.expectError("SyntaxError", "Unexpected token ']'", () => JSON.parse("]"));
Test.expectError("SyntaxError", "Unexpected token '}' in JSON", () => JSON.parse("{\"id\":0,}"));
Test.expectError("SyntaxError", "Unexpected token '}' in JSON", () => JSON.parse("{\"�\":\"0\",}"));
Test.expectError("SyntaxError", "Unexpected token '}'", () => JSON.parse("{ \"foo\" : \"bar\", \"a\" }"));
Test.expectError("SyntaxError", "Unexpected token '*' in JSON", () => JSON.parse("[*]"));
Test.expectError("SyntaxError", "Unexpected token '*'", () => JSON.parse("*"));
Test.expectError("SyntaxError", "Unexpected token '/'", () => JSON.parse("{\"a\":/*comment*/\"b\"}"));
Test.expectError("SyntaxError", "Unexpected token '\\'", () => JSON.parse("[\\n]"));
Test.expectError("SyntaxError", "Unexpected token '\\'", () => JSON.parse("[\\u000A\"\"]"));
Test.expectError("SyntaxError", "Unexpected token '\\'", () => JSON.parse("[\\u0020\"asd\"]"));
Test.expectError("SyntaxError", "Unexpected token '\\f'", () => JSON.parse("[\f]"));
Test.expectError("SyntaxError", "Unexpected token '\\u00E5' in JSON", () => JSON.parse("å"));
Test.expectError("SyntaxError", "Unexpected token '\\u00E9'", () => JSON.parse("[é]"));
Test.expectError("SyntaxError", "Unexpected token '\\u2060' in JSON", () => JSON.parse("[⁠]"));
Test.expectError("SyntaxError", "Unexpected token '\\uD83C\\uDDE8' in JSON", () => JSON.parse("{🇨🇭}"));
Test.expectError("SyntaxError", "Unexpected token '\\uFEFF' in JSON", () => JSON.parse("﻿"));
Test.expectError("SyntaxError", "Unexpected token '\\uFF11'", () => JSON.parse("[１]"));
Test.expectError("SyntaxError", "Unexpected token '\\uFFFD' in JSON", () => JSON.parse("[0�]\r\n"));
Test.expectError("SyntaxError", "Unexpected token '\\uFFFD' in JSON", () => JSON.parse("[123�]"));
Test.expectError("SyntaxError", "Unexpected token '\\uFFFD' in JSON", () => JSON.parse("[1e1�]"));
Test.expectError("SyntaxError", "Unexpected token '\\uFFFD' in JSON", () => JSON.parse("[�]"));
Test.expectError("SyntaxError", "Unexpected token '\\uFFFD'", () => JSON.parse("�"));
Test.expectError("SyntaxError", "Unexpected token '\\uFFFD'", () => JSON.parse("�{}"));
Test.expectError("SyntaxError", "Unexpected token '\\x00'", () => JSON.parse("[\u0000]"));
Test.expectError("SyntaxError", "Unexpected token '+' in JSON", () => JSON.parse("[++1234]"));
Test.expectError("SyntaxError", "Unexpected token '+' in JSON", () => JSON.parse("[+1]"));
Test.expectError("SyntaxError", "Unexpected token '+' in JSON", () => JSON.parse("[+Inf]"));
Test.expectError("SyntaxError", "Unexpected token '+' in JSON", () => JSON.parse("[1+2]"));
Test.expectError("SyntaxError", "Unexpected token '<'", () => JSON.parse("[<null>]"));
Test.expectError("SyntaxError", "Unexpected token '<'", () => JSON.parse("<.>"));
Test.expectError("SyntaxError", "Unexpected token '0' in JSON", () => JSON.parse("[1 000.0]"));
Test.expectError("SyntaxError", "Unexpected token '1' in JSON", () => JSON.parse("[-01]"));
Test.expectError("SyntaxError", "Unexpected token '1' in JSON", () => JSON.parse("[-012]"));
Test.expectError("SyntaxError", "Unexpected token '1' in JSON", () => JSON.parse("[012]"));
Test.expectError("SyntaxError", "Unexpected token '1' in JSON", () => JSON.parse("{\"a\":\"a\" 123}"));
Test.expectError("SyntaxError", "Unexpected token '1' in JSON", () => JSON.parse("{1:1}"));
Test.expectError("SyntaxError", "Unexpected token '9' in JSON", () => JSON.parse("{9999E9999:1}"));
Test.expectError("SyntaxError", "Unexpected token 'a' in JSON", () => JSON.parse("[1.2a-3]"));
Test.expectError("SyntaxError", "Unexpected token 'a' in JSON", () => JSON.parse("[a�]"));
Test.expectError("SyntaxError", "Unexpected token 'a' in JSON", () => JSON.parse("{a: \"b\"}"));
Test.expectError("SyntaxError", "Unexpected token 'a' in JSON", () => JSON.parse("abc"));
Test.expectError("SyntaxError", "Unexpected token 'a'", () => JSON.parse("aå"));
Test.expectError("SyntaxError", "Unexpected token 'b' in JSON", () => JSON.parse("{\"a\" b}"));
Test.expectError("SyntaxError", "Unexpected token 'f' in JSON", () => JSON.parse("[-123.123foo]"));
Test.expectError("SyntaxError", "Unexpected token 'H' in JSON", () => JSON.parse("[1.8011670033376514H-308]"));
Test.expectError("SyntaxError", "Unexpected token 'I' in JSON", () => JSON.parse("[Inf]"));
Test.expectError("SyntaxError", "Unexpected token 'I' in JSON", () => JSON.parse("[Infinity]"));
Test.expectError("SyntaxError", "Unexpected token 'k' in JSON", () => JSON.parse("{key: 'value'}"));
Test.expectError("SyntaxError", "Unexpected token 'N' in JSON", () => JSON.parse("[NaN]"));
Test.expectError("SyntaxError", "Unexpected token 'n' in JSON", () => JSON.parse("{null:null,null:null}"));
Test.expectError("SyntaxError", "Unexpected token 't' in JSON", () => JSON.parse("[1 true]"));
Test.expectError("SyntaxError", "Unexpected token 't'", () => JSON.parse("[\"x\", truth]"));
Test.expectError("SyntaxError", "Unexpected token 'T'", () => JSON.parse("[True]"));
Test.expectError("SyntaxError", "Unexpected token 'x' in JSON", () => JSON.parse("[-1x]"));
Test.expectError("SyntaxError", "Unexpected token 'x' in JSON", () => JSON.parse("[0x1]"));
Test.expectError("SyntaxError", "Unexpected token 'x' in JSON", () => JSON.parse("[0x42]"));
Test.expectError("SyntaxError", "Unexpected token 'x' in JSON", () => JSON.parse("[x"));
Test.expectError("SyntaxError", `Unexpected token '"' in JSON`, () => JSON.parse("{\"a\" \"b\"}"));
Test.expectError("SyntaxError", `Unexpected token "'" in JSON`, () => JSON.parse("['single quote']"));
Test.expectError("SyntaxError", `Unexpected token "'" in JSON`, () => JSON.parse("{'a':0}"));
Test.expectError("SyntaxError", `Unexpected token "'" in JSON`, () => JSON.parse("{'a'"));
Test.expectError("SyntaxError", `Unexpected token "'"`, () => JSON.parse("['"));